name: Shell Commands 

#on: [push]
on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    #timeout-minutes:  360 lo cancela si toma mas de este tiempo
    steps: 
      - name: echo a string
        run: echo "Hello World"
        timeout-minutes: 0
        #continue-on-error: true
      - name: multiline script 
        #if: failure()
        run: |
           node -v 
           npm -v
      - name: python Command 
        run: |
          import platform 
          print
          (platform.processor())
        shell: python
  run-windwos-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location 
      - name: Directory Bash 
        run: pwd 
        shell: bash 